### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by 16Lab-Persicaria** [zaixia108/WTautoFull#13]
新装的系统（64位win7），发现安装后点开程序窗口闪一下就没了，下方任务栏可以看到窗口但是点不开，是否需要安装额外的环境
疑难解答有如下报错
Failed to execute script 'UI' due to unhandled exception: <built-in function pop_container_stack>
returned a result with an error set
---------------------------------------------------------------------------------------------------------------------------------------------------
Exception: Error: [1000] Message: 	Font file could not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dearpygui\dearpygui.py", line 1866, in font_registry
  File "UI.py", line 53, in <module>
  File "contextlib.py", line 113, in __enter__
  File "dearpygui\dearpygui.py", line 1839, in font
SystemError: <built-in function add_font> returned a result with an error set

During handling of the above exception, another exception occurred:

Exception: Error: [1009] Message: 	No container to pop.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "UI.py", line 56, in <module>
  File "contextlib.py", line 131, in __exit__
  File "dearpygui\dearpygui.py", line 1868, in font_registry
SystemError: <built-in function pop_container_stack> returned a result with an error set

**Comment by 16Lab-Persicaria** [comment]
装个win10解决了
