### ISSUE TITLE
在虚拟机中无法打开程序

### ISSUE THREAD

**Issue by chainsword** [zaixia108/WTautoFull#21]
报错内容
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: 参数错误。

**Comment by WJerry66** [comment]
有个1.2.0的版本
哦，不对，说错了，是win7
新的大概只能在win10
在那个二维码的链接里面

**Comment by WJerry66** [comment]
引用自up108
